import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
  { path: '', redirectTo: 'Home', pathMatch: 'full' },
  { path: 'Home', loadChildren: './pages/home/home.module#HomePageModule' },
  { path: 'List', loadChildren: './pages/list/list.module#ListPageModule' },
  { path: 'About', loadChildren: './pages/about/about.module#AboutPageModule' },
  { path: 'ActionSheet1', loadChildren: './pages/action-sheet1/action-sheet.module#ActionSheetPageModule1' },
  { path: 'ActionSheet2', loadChildren: './pages/action-sheet2/action-sheet.module#ActionSheetPageModule2' },
  { path: 'Buttons', loadChildren: './pages/buttons/buttons.module#ButtonsPageModule' },
  { path: 'ToolbarButtons', loadChildren: './pages/toolbar-buttons/toolbar-buttons.module#ToolbarButtonsPageModule' },
  { path: 'Card', loadChildren: './pages/card/card.module#CardPageModule' },
  { path: 'Checkbox', loadChildren: './pages/checkbox/checkbox.module#CheckboxPageModule' },
  { path: 'ActionSheetController', loadChildren: './pages/action-sheet-controller/action-sheet-controller.module#ActionSheetControllerPageModule' },
  { path: 'AlertController', loadChildren: './pages/alert-controller/alert-controller.module#AlertControllerPageModule' },
  { path: 'Alert', loadChildren: './pages/alert/alert.module#AlertPageModule' },
  { path: 'Anchor', loadChildren: './pages/anchor/anchor.module#AnchorPageModule' },
  { path: 'AnimationController', loadChildren: './pages/animation-controller/animation-controller.module#AnimationControllerPageModule' },
  { path: 'App', loadChildren: './pages/app/app.module#AppPageModule' },
  { path: 'Avatar', loadChildren: './pages/avatar/avatar.module#AvatarPageModule' },
  { path: 'BackButton', loadChildren: './pages/back-button/back-button.module#BackButtonPageModule' },
  { path: 'Backdrop', loadChildren: './pages/backdrop/backdrop.module#BackdropPageModule' },
  { path: 'Badge', loadChildren: './pages/badge/badge.module#BadgePageModule' },
  { path: 'Button', loadChildren: './pages/button/button.module#ButtonPageModule' },
  { path: 'CardContent', loadChildren: './pages/card-content/card-content.module#CardContentPageModule' },
  { path: 'CardHeader', loadChildren: './pages/card-header/card-header.module#CardHeaderPageModule' },
  { path: 'CardSubtitle', loadChildren: './pages/card-subtitle/card-subtitle.module#CardSubtitlePageModule' },
  { path: 'CardTitle', loadChildren: './pages/card-title/card-title.module#CardTitlePageModule' },
  { path: 'ChipButton', loadChildren: './pages/chip-button/chip-button.module#ChipButtonPageModule' },
  { path: 'ChipIcon', loadChildren: './pages/chip-icon/chip-icon.module#ChipIconPageModule' },
  { path: 'Chip', loadChildren: './pages/chip/chip.module#ChipPageModule' },
  { path: 'Col', loadChildren: './pages/col/col.module#ColPageModule' },
  { path: 'Content1',     loadChildren: './pages/content1/content.module#ContentPageModule' },
  { path: 'Content2',     loadChildren: './pages/content2/content.module#ContentPageModule2' },
  { path: 'Datetime', loadChildren: './pages/datetime/datetime.module#DatetimePageModule' },
  { path: 'FabButton', loadChildren: './pages/fab-button/fab-button.module#FabButtonPageModule' },
  { path: 'FabList', loadChildren: './pages/fab-list/fab-list.module#FabListPageModule' },
  { path: 'Fab', loadChildren: './pages/fab/fab.module#FabPageModule' },
  { path: 'Footer', loadChildren: './pages/footer/footer.module#FooterPageModule' },
  { path: 'Grid', loadChildren: './pages/grid/grid.module#GridPageModule' },
  { path: 'Header', loadChildren: './pages/header/header.module#HeaderPageModule' },
  { path: 'HideWhen', loadChildren: './pages/hide-when/hide-when.module#HideWhenPageModule' },
  { path: 'Icon', loadChildren: './pages/icon/icon.module#IconPageModule' },
  { path: 'Img', loadChildren: './pages/img/img.module#ImgPageModule' },
  { path: 'InfiniteScrollContent', loadChildren: './pages/infinite-scroll-content/infinite-scroll-content.module#InfiniteScrollContentPageModule' },
  { path: 'InfiniteScroll', loadChildren: './pages/infinite-scroll/infinite-scroll.module#InfiniteScrollPageModule' },
  { path: 'Input', loadChildren: './pages/input/input.module#InputPageModule' },
  { path: 'ItemDivider', loadChildren: './pages/item-divider/item-divider.module#ItemDividerPageModule' },
  { path: 'ItemGroup', loadChildren: './pages/item-group/item-group.module#ItemGroupPageModule' },
  { path: 'ItemOption', loadChildren: './pages/item-option/item-option.module#ItemOptionPageModule' },
  { path: 'ItemOptions', loadChildren: './pages/item-options/item-options.module#ItemOptionsPageModule' },
  { path: 'ItemSliding', loadChildren: './pages/item-sliding/item-sliding.module#ItemSlidingPageModule' },
  { path: 'Item', loadChildren: './pages/item/item.module#ItemPageModule' },
  { path: 'Label', loadChildren: './pages/label/label.module#LabelPageModule' },
  { path: 'ListHeader', loadChildren: './pages/list-header/list-header.module#ListHeaderPageModule' },
  { path: 'LoadingController', loadChildren: './pages/loading-controller/loading-controller.module#LoadingControllerPageModule' },
  { path: 'Loading', loadChildren: './pages/loading/loading.module#LoadingPageModule' },
  { path: 'MenuButton', loadChildren: './pages/menu-button/menu-button.module#MenuButtonPageModule' },
  { path: 'MenuController', loadChildren: './pages/menu-controller/menu-controller.module#MenuControllerPageModule' },
  { path: 'MenuToggle', loadChildren: './pages/menu-toggle/menu-toggle.module#MenuTogglePageModule' },
  { path: 'Menu', loadChildren: './pages/menu/menu.module#MenuPageModule' },
  { path: 'ModalController', loadChildren: './pages/modal-controller/modal-controller.module#ModalControllerPageModule' },
  { path: 'Modal', loadChildren: './pages/modal/modal.module#ModalPageModule' },
  { path: 'NavPop', loadChildren: './pages/nav-pop/nav-pop.module#NavPopPageModule' },
  { path: 'NavPush', loadChildren: './pages/nav-push/nav-push.module#NavPushPageModule' },
  { path: 'NavSetRoot', loadChildren: './pages/nav-set-root/nav-set-root.module#NavSetRootPageModule' },
  { path: 'Nav', loadChildren: './pages/nav/nav.module#NavPageModule' },
  { path: 'Note', loadChildren: './pages/note/note.module#NotePageModule' },
  { path: 'PickerColumn', loadChildren: './pages/picker-column/picker-column.module#PickerColumnPageModule' },
  { path: 'PickerController', loadChildren: './pages/picker-controller/picker-controller.module#PickerControllerPageModule' },
  { path: 'Picker', loadChildren: './pages/picker/picker.module#PickerPageModule' },
  { path: 'Popovercontroller', loadChildren: './pages/popovercontroller/popovercontroller.module#PopovercontrollerPageModule' },
  { path: 'Popover', loadChildren: './pages/popover/popover.module#PopoverPageModule' },
  { path: 'RadioGroup', loadChildren: './pages/radio-group/radio-group.module#RadioGroupPageModule' },
  { path: 'Radio', loadChildren: './pages/radio/radio.module#RadioPageModule' },
  { path: 'Range', loadChildren: './pages/range/range.module#RangePageModule' },
  { path: 'RefresherContent', loadChildren: './pages/refresher-content/refresher-content.module#RefresherContentPageModule' },
  { path: 'Refresher', loadChildren: './pages/refresher/refresher.module#RefresherPageModule' },
  { path: 'ReorderGroup', loadChildren: './pages/reorder-group/reorder-group.module#ReorderGroupPageModule' },
  { path: 'Reorder', loadChildren: './pages/reorder/reorder.module#ReorderPageModule' },
  { path: 'RippleEffect', loadChildren: './pages/ripple-effect/ripple-effect.module#RippleEffectPageModule' },
  { path: 'RouteRedirect', loadChildren: './pages/route-redirect/route-redirect.module#RouteRedirectPageModule' },
  { path: 'Route', loadChildren: './pages/route/route.module#RoutePageModule' },
  { path: 'RouterOutlet', loadChildren: './pages/router-outlet/router-outlet.module#RouterOutletPageModule' },
  { path: 'Router', loadChildren: './pages/router/router.module#RouterPageModule' },
  { path: 'Row', loadChildren: './pages/row/row.module#RowPageModule' },
  { path: 'Searchbar', loadChildren: './pages/searchbar/searchbar.module#SearchbarPageModule' },
  { path: 'SegmentButton', loadChildren: './pages/segment-button/segment-button.module#SegmentButtonPageModule' },
  { path: 'Segment', loadChildren: './pages/segment/segment.module#SegmentPageModule' },
  { path: 'SelectOption', loadChildren: './pages/select-option/select-option.module#SelectOptionPageModule' },
  { path: 'SelectPopover', loadChildren: './pages/select-popover/select-popover.module#SelectPopoverPageModule' },
  { path: 'Select', loadChildren: './pages/select/select.module#SelectPageModule' },
  { path: 'ShowWhen', loadChildren: './pages/show-when/show-when.module#ShowWhenPageModule' },
  { path: 'SkeletonText', loadChildren: './pages/skeleton-text/skeleton-text.module#SkeletonTextPageModule' },
  { path: 'Slide', loadChildren: './pages/slide/slide.module#SlidePageModule' },
  { path: 'Slides', loadChildren: './pages/slides/slides.module#SlidesPageModule' },
  { path: 'Spinner', loadChildren: './pages/spinner/spinner.module#SpinnerPageModule' },
  { path: 'SplitPane', loadChildren: './pages/split-pane/split-pane.module#SplitPanePageModule' },
  { path: 'Tab', loadChildren: './pages/tab/tab.module#TabPageModule' },
  { path: 'Tabbar', loadChildren: './pages/tabbar/tabbar.module#TabbarPageModule' },
  { path: 'Tabs', loadChildren: './pages/tabs/tabs.module#TabsPageModule' },
  { path: 'Text', loadChildren: './pages/text/text.module#TextPageModule' },
  { path: 'Textarea', loadChildren: './pages/textarea/textarea.module#TextareaPageModule' },
  { path: 'Thumbnail', loadChildren: './pages/thumbnail/thumbnail.module#ThumbnailPageModule' },
  { path: 'Title', loadChildren: './pages/title/title.module#TitlePageModule' },
  { path: 'ToastController', loadChildren: './pages/toast-controller/toast-controller.module#ToastControllerPageModule' },
  { path: 'Toast', loadChildren: './pages/toast/toast.module#ToastPageModule' },
  { path: 'Toggle', loadChildren: './pages/toggle/toggle.module#TogglePageModule' },
  { path: 'Toolbar', loadChildren: './pages/toolbar/toolbar.module#ToolbarPageModule' },
  { path: 'VirtualScroll1', loadChildren: './pages/virtual-scroll1/virtual-scroll.module#VirtualScrollPageModule1' },
  { path: 'VirtualScroll', loadChildren: './pages/virtual-scroll/virtual-scroll.module#VirtualScrollPageModule' }

];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
